### ISSUE TITLE
Installations fails

### ISSUE THREAD

**Issue by jappyjan** [matthewlloyd/klipper#2]
Whenever i try to install this on a pi (3 or 4, both same) with a fresh raspbian i get the following error and the installation fails...

```
Building wheel for greenlet (setup.py) ... done
  Created wheel for greenlet: filename=greenlet-0.4.15-cp27-cp27mu-linux_armv7l.whl size=42552 sha256=46e3e0089820a3ca7d115c8e7172e01da7a94b9d386e46c1a771a9bd7ac0f357
  Stored in directory: /home/pi/.cache/pip/wheels/3f/e6/02/74f0984bdb2da68f7e101762ade672f06c09f145d821d0a8ff
  Building wheel for Pillow (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/pi/klippy-env/bin/python2 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-IURqwk/pillow/setup.py'"'"'; __file__='"'"'/tmp/pip-install-IURqwk/pillow/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-GF9Em2
       cwd: /tmp/pip-install-IURqwk/pillow/
  Complete output (143 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-armv7l-2.7
  creating build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImageWin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/PixarImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/EpsImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/PcdImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/MicImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/FontFile.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/BlpImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/_util.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/PyAccess.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImageColor.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/BmpImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImageMode.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/IcnsImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/_tkinter_finder.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/MpoImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/JpegPresets.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/PngImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/BdfFontFile.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/SpiderImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImageQt.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImageGrab.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/Jpeg2KImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImageFont.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/TiffImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/DdsImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/IptcImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/SunImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/PcxImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/GimpGradientFile.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ExifTags.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/Hdf5StubImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/BufrStubImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/IcoImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImageTk.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/PSDraw.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/features.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/XVThumbImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/GifImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/JpegImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImageSequence.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/PsdImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/_binary.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/WalImageFile.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/FpxImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/OleFileIO.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImagePalette.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImageMath.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/XbmImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/GbrImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ContainerIO.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/GimpPaletteFile.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/GribStubImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/DcxImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/SgiImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImageShow.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/FliImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImtImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/CurImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImageEnhance.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/PalmImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/WebPImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/McIdasImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/MspImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImageStat.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImageMorph.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/TarIO.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/WmfImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/MpegImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/TiffTags.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImageCms.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/PaletteFile.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImageDraw2.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/__init__.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImageFile.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImageChops.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/_version.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/TgaImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/GdImageFile.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/PdfImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImagePath.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/PpmImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/PdfParser.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImageFilter.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImageOps.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/Image.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/XpmImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/FtexImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImageDraw.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/ImageTransform.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/PcfFontFile.py -> build/lib.linux-armv7l-2.7/PIL
  copying src/PIL/FitsStubImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  running egg_info
  writing src/Pillow.egg-info/PKG-INFO
  writing top-level names to src/Pillow.egg-info/top_level.txt
  writing dependency_links to src/Pillow.egg-info/dependency_links.txt
  reading manifest file 'src/Pillow.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching '*.c'
  warning: no files found matching '*.h'
  warning: no files found matching '*.sh'
  no previously-included directories found matching 'docs/_static'
  warning: no previously-included files found matching '.appveyor.yml'
  warning: no previously-included files found matching '.coveragerc'
  warning: no previously-included files found matching '.codecov.yml'
  warning: no previously-included files found matching '.editorconfig'
  warning: no previously-included files found matching '.landscape.yaml'
  warning: no previously-included files found matching '.readthedocs.yml'
  warning: no previously-included files found matching '.travis'
  warning: no previously-included files found matching '.travis/*'
  warning: no previously-included files found matching 'tox.ini'
  warning: no previously-included files matching '.git*' found anywhere in distribution
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files matching '*.so' found anywhere in distribution
  writing manifest file 'src/Pillow.egg-info/SOURCES.txt'
  running build_ext


  The headers or library files could not be found for jpeg,
  a required dependency when compiling Pillow from source.

  Please see the install instructions at:
     https://pillow.readthedocs.io/en/latest/installation.html

  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-IURqwk/pillow/setup.py", line 812, in <module>
      raise RequiredDependencyException(msg)
  __main__.RequiredDependencyException:

  The headers or library files could not be found for jpeg,
  a required dependency when compiling Pillow from source.

  Please see the install instructions at:
     https://pillow.readthedocs.io/en/latest/installation.html


  ----------------------------------------
  ERROR: Failed building wheel for Pillow
  Running setup.py clean for Pillow
  Building wheel for numpy (setup.py) ... \client_loop: send disconnect: Broken pipe
```

**Comment by matthewlloyd** [comment]
Try

> sudo apt install libjpeg-dev
